export const RESPONSES = {
  SUCCESS: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NOCONTENT: 204,
  BADREQUEST: 400,
  UN_AUTHORIZED: 401,
  INVALID_REQ: 422,
  FORBIDDEN: 403,
  NOTFOUND: 404,
  CONFLICT: 409,
  TIMEOUT: 408,
  TOOMANYREQ: 429,
  INTERNALSERVER: 500,
  BADGATEWAYS: 502,
  SERVICEUNAVILABLE: 503,
  GATEWAYTIMEOUT: 504,
};
export const RES_MSG = {
  SERVER_SUCCESS: 'Server is running',
  NO_DATA: 'No data found for this request',
  BADREQUEST: 'Not a Valid Request',
  INTERNAL_SERVER_ERROR: 'Internal Server Error',
  REQUEST_EMPTY: 'Kindly fill the required details',
  SMTHNG_WRNG: 'Something went wrong',
  UNAUTHORISED:
    'You are not Authorised. Kindly login again with your credentials.',
  DATA_SUCCESS: 'Data Fetched Successfully',
  UNAUTHORISED_ACCESS: 'Unauthorised Access',
  NO_USER: 'No record found for such credentials',
  INVALID_USER: 'User data not found',
  DATA_FETCH_ERROR: 'Error in fetching data',
  USER_CREATED_SUCCESS: 'User registered successfully',
  USER_CREATE_ERROR: 'Error in creating User',
  USER_DELETED: 'User Deleted Successfully',
  USER_FETCH_ERROR: 'Error in fetching User',
  USER_UPDATION_SUCCESS: 'User Updated Successfully',
  USER_UPDATION_ERROR: 'Error in updating User',
  USER_ALREADY_EXIST: 'User Already exist',
  USER_AVAILABLE: 'User Available',
  EMAIL_FOUND: 'Email Found',
  EMAIL_NOT_FOUND: 'Email not found',
  DATA_UPDATED: 'Data Updated Successfully',
  DATA_ADDED: 'Data Added Successfully',
  DATA_UPDATION_ERROR: 'Error in Updating data',
  DATA_ADDED_ERROR: 'Error in adding data',
  LOGIN_FAILURE: 'Invalid credentials',
  PASSWORD_CHANGED: 'Password changed successfully',
  LOGIN_SUCCESS: 'Logged in Successfully!!',
  ACTION_NOT_ALLOWED: 'Action not allowed',
  INVALID_CREDENTIALS: 'Invalid credentials',
  NOTES_FETCH_SUCCESS: 'Notes fetched successfully',
  NOTE_CREATE_SUCCESS: 'Notes created successfully',
  NOTE_NOT_FOUND: 'Note not found',
  NOTE_UPDATE_SUCCESS: 'Note updated successfully',
  NOTE_DELETE_SUCCESS: 'Note deleted successfully',
  CREATE_NOTE_FAILURE: 'Could not create note',
  MISSING_JWT_TOKEN: 'Invalid jwt auth header',
  DUPLICATE_NOTE: 'Note with same title already exists',
};
