export const RESPONSES = {
  SUCCESS: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NOCONTENT: 204,
  BADREQUEST: 400,
  UN_AUTHORIZED: 401,
  INVALID_REQ: 422,
  FORBIDDEN: 403,
  NOTFOUND: 404,
  CONFLICT: 409,
  TIMEOUT: 408,
  TOOMANYREQ: 429,
  INTERNALSERVER: 500,
  BADGATEWAYS: 502,
  SERVICEUNAVILABLE: 503,
  GATEWAYTIMEOUT: 504,
};
export const RES_MSG = {
  SERVER_SUCCESS: 'Server is running',
  NO_DATA: 'No data found for this request',
  BADREQUEST: 'Not a Valid Request',
  INTERNAL_SERVER_ERROR: 'Internal Server Error',
  REQUEST_EMPTY: 'Kindly fill the required details',
  SMTHNG_WRNG: 'Something went wrong',
  UNAUTHORISED:
    'You are not Authorised. Kindly login again with your credentials.',
  DUPLICATE_DATA: 'Data already Available',
  DATA_SUCCESS: 'Data Fetched Successfully',
  UNAUTHORISED_ACCESS: 'Unauthorised Access',
  TOO_MANY_REQ: 'Too many Requests from this IP, Please try again Later',
  NO_USER: 'No record found for such credentials',
  INVALID_USER: 'User data not found',
  DATA_FETCH_ERROR: 'Error in fetching data',
  USER_CREATED_SUCCESS: 'User registered successfully',
  USER_CREATE_ERROR: 'Error in creating User',
  USER_DELETED: 'User Deleted Successfully',
  USER_FETCH_ERROR: 'Error in fetching User',
  USER_UPDATION_SUCCESS: 'User Updated Successfully',
  USER_UPDATION_ERROR: 'Error in updating User',
  USER_ALREADY_EXIST: 'User Already exist',
  USER_AVAILABLE: 'User Available',
  EMAIL_FOUND: 'Email Found',
  EMAIL_NOT_FOUND: 'Email not found',
  DATA_UPDATED: 'Data Updated Successfully',
  DATA_ADDED: 'Data Added Successfully',
  DATA_UPDATION_ERROR: 'Error in Updating data',
  DATA_ADDED_ERROR: 'Error in adding data',
  ADMIN_DATA_ERROR: 'Error in adding admin records',
  SIGNUP_SUCCESSFUL:
    'Sign Up successfull. Please check your email for further process.',
  REFERRAL_CODE_ERROR: 'No such Referral code found',
  REACHED_ADMIN_NODE: 'Reached the Admin Node',
  LEVEL_ADD_ERROR: 'Error in Adding Levels to the database',
  LEVEL_FETCH_ERROR: 'Error in Fetching Levels Data',
  LEVEL_UPDATED_SUCCESS: 'Level of the user updated Successfully',
  LEVEL_UPDATE_ERROR: 'Error in updating level of user',
  BUSINESS_UPDATE_ERROR:
    'Error in updating Referral Business amount or reached Admin',
  BLOCK_UPDATION_SUCCESS: 'Block Updated Successfully in database',
  BLOCK_UPDATION_ERROR: 'Error in updating block in the database',
  ACHIEVER_BONUS_ERROR: 'Error in updating records of achiever bonus',
  EARNING_RECORD_CREATION_ERROR: 'Error in creating earning record ledger',
  REFERRAL_BONUS_ERROR: 'Error in updating records of referral bonus',
  REWARD_BONUS_ERROR: 'Error in updating records for reward bonus',
  REWARD_BONUS_UPDATE: 'Reward Bonus updated successfully',
  OVERRIDE_BONUS_ERROR:
    'Error in creating or updating records of overriding bonus',
  LEVEL_NOT_FOUND: 'Level not found in database',
  TRANSACTION_FETCH_ERROR: 'Error in getting transaction for given userId',
  EARNING_TYPE_UPDATION_ERROR: 'Error in updating the earning type',
  CLAIMABLE_AMOUNT_SUCCESS: 'Amount made claimable successfully',
  CLAIMED_AMOUNT_SUCCESS: 'Claimed amount updated Successfully',
  EARNING_TYPE_MISMATCH: 'Earning type does not match',
  ALREADY_CLAIMED: 'Amount already claimed by the user',
  FREEZE_ID_ERROR: 'NO such freeze ID found',
  VESTING_FETCH_ERROR: 'Error in fetching vesting point',
  RABBIT_MQ_SUCCESS: 'RabbitMq Server connected Successfully',
  RABBIT_MQ_ERROR: 'Error in connecting RabbitMQ server',
  RABBIT_MQ_CHANNEL_ERROR: 'Error in creating channel for rabbitMQ',
  EMAIL_SENT: 'Email sent successfully',
  EMAIL_FAIL: 'Email failed to sent',
  PASSWORD_GENERATION_ERROR: 'Error in generating password of user',
  LOGIN_FAILURE: 'Invalid credentials',
  PASSWORD_CHANGED: 'Password changed successfully',
  LOGIN_SUCCESS: 'Logged in Successfully!!',
  TOKEN_SAVED: 'Token saved successfully to the database',
  TOKEN_ERROR: 'Error in creating or saving JWT token',
  TOKEN_UPDATED: 'Successfully updated token',
  TOKEN_VALID_ERROR: 'Not a valid token',
  WALLET_ADDRESS_SUCCESS: 'Wallet Address added Successfully to the user',
  PASSWORD_MISMATCH: 'Invalid old password',
  TRANSACTION_ERROR: 'Error in processing transactions',
  TRANSACTION_SUCCESS:
    'Successfully executed transactions, fund transferred to users.',
  MONTHLY_EARNING_ERROR: 'Error in updating monthly earning of user',
  TOKEN_DISTRIBUTED_SUCCESSFULLY: 'Tokens distributed successfully',
  USER_BLOCKED: 'User blocked !!',
  USER_UNBLOCKED: 'User unblocked !!',
  INVALID_FILTER: 'Invalid filter',
  ACTION_NOT_ALLOWED: 'Action not allowed',
  NETWORK_ARRAY_ERROR: 'Error in fetching network array',
  CURRENT_PRICE_FETCHED: 'Current price fetched successfully',
  CURRENT_PRICE_ERROR: 'Error in fetching current price of token',
  TOKEN_NOT_FOUND: 'Token not found in database',
  TOKEN_REFRESH_ERROR:
    'Your session has expired. Please log in again to continue.',
  VERIFY_OTP: 'Check your mail and verfiy the OTP',
  INVALID_OTP: 'Invalid OTP',
  OTP_VERIFIED: 'OTP verified successfully',
  INAVLID_DISTRIBUTION_LIST_FORMAT: 'Inavlid format for distribution list',
  PASSWORD_CHANGE_REQUIRED: 'You are required to change your password',
  NOTIFICATION_SUCCESS: 'Notification send successfully',
  NOTIFICATION_ERROR: 'Error in sending notification',
  VERIFICATION_STATUS_ERROR: 'Error in updating the verification status',
  RESEND_LIMIT: (time: number) =>
    `You have reached the OTP resend limit. Please try again after ${time} minutes`,
  OTP_EXPIRED: 'OTP expired',
  SESSION_ERROR: 'Unable to Find Session',
  SESSION_AVAILABLE: 'Session Available',
  LOGOUT_SUCCESS: 'Logout successfully',
  INVALID_CREDENTIALS: 'Invalid credentials',
  NOTES_FETCH_SUCCESS: 'Notes fetched successfully',
  NOTE_CREATE_SUCCESS: 'Notes created successfully',
  NOTE_NOT_FOUND: 'Note not found',
  NOTE_UPDATE_SUCCESS: 'Note updated successfully',
  NOTE_DELETE_SUCCESS: 'Note deleted successfully',
  CREATE_NOTE_FAILURE: 'Could not create note',
  MISSING_JWT_TOKEN: 'Invalid jwt auth header',
  DUPLICATE_NOTE: 'Note with same title already exists',
};
